IT21812262/FleetManagementSysyem

backend/server.js

merge main branch with sub branch

Inventory management

---

backend/models/fuel/fuel_entry.js
backend/routes/fuel_entry.js

changing file name and coding the Inventory.js file

chnage file

---

frontend/package-lock.json
frontend/package.json
frontend/src/Components/AddSupplier.js
frontend/src/Components/Header.js

Design create files and add header.js file

Design create files and add header.js file

---

backend/models/trip/trip.js
backend/routes/trip.js
backend/server.js

Completing trip.js code inside models folder

Completing trip.js code inside models folder

---

backend/models/maintenance/maintenance.js
backend/routes/maintenance.js
backend/server.js

Committing Changes in the maintenance management System

Maintenance management system

---

frontend/src/Components/Supplier/AddSupplier.css
frontend/src/Components/Supplier/AddSupplier.js
frontend/src/Components/Supplier/AllSupplier.css
frontend/src/Components/Supplier/AllSupplier.js
frontend/src/Components/Supplier/UniqueSupplier.css
frontend/src/Components/Supplier/UniqueSupplier.js
frontend/src/Components/Supplier/UpdateSupplier.css
frontend/src/Components/Supplier/UpdateSupplier.js
frontend/src/index.js

validating updating operations and css files

validating updating operations and css files

---

frontend/src/Components/Supplier/AddSupplier.js
frontend/src/Components/Supplier/UniqueSupplier.js
frontend/src/Components/Supplier/UpdateSupplier.js

add calculation part

---

frontend/src/index.js

correction in index.js

---

frontend/src/Components/Rent/AddRent.js
frontend/src/Components/Rent/AllRent.js
frontend/src/Components/Rent/Rent.js
frontend/src/Components/Rent/UniqueRent.js
frontend/src/Components/Rent/UpdateRent.js
frontend/src/index.js

Allrent changes

---

backend/server.js
frontend/src/index.js

Fuel management system

---

backend/routes/fuelentry.js
frontend/src/Components/Fuel/FuelEntry/AddFuelEntry.js
frontend/src/Components/Fuel/FuelEntry/AllFuelEntry.js
frontend/src/Components/Fuel/FuelEntry/UniqueFuelEntry.js
frontend/src/Components/Fuel/FuelEntry/UpdateFuelEntry.js
frontend/src/Components/Fuel/FuelStock/AddFuelStock.js
frontend/src/Components/Fuel/FuelStock/AllFuelStock.js
frontend/src/Components/Fuel/FuelStock/UniqueFuelStock.js
frontend/src/Components/Fuel/FuelStock/UpdateFuelStock.js
frontend/src/index.js

Created New button connections

Created New button connections

---

backend/models/rent/rent.js
frontend/package-lock.json
frontend/package.json
frontend/src/Components/Rent/AddRent.js
frontend/src/Components/Rent/AllRent.js
frontend/src/Components/Rent/Rent.js
frontend/src/Components/Rent/UniqueRent.js
frontend/src/Components/Rent/UpdateRent.js

completed rent management

---

backend/routes/employees.js
backend/server.js
frontend/package-lock.json
frontend/package.json
frontend/src/Components/Employee/AddEmployee.js
frontend/src/Components/Employee/AllEmployee.js
frontend/src/Components/Employee/Employee.js
frontend/src/Components/Employee/UpdateEmployee.js
frontend/src/index.js

adding frontend code

---

backend/models/maintenance/maintenance.js
backend/routes/maintenance.js
frontend/public/index.html
frontend/src/Components/Maintenance/AddMaintenance.js
frontend/src/Components/Maintenance/AllMaintenance.css
frontend/src/Components/Maintenance/AllMaintenance.js
frontend/src/Components/Maintenance/Maintenance.js
frontend/src/Components/Maintenance/UniqueMaintenance.js
frontend/src/Components/Maintenance/UniqueMaintenanceJob.css
frontend/src/Components/Maintenance/UpdateMaintenance.css
frontend/src/Components/Maintenance/UpdateMaintenance.js
frontend/src/index.js

80% completed backend and frontend

finalize frontend and backend

---

frontend/src/Components/Inventory/AddInventory.css
frontend/src/Components/Inventory/AddInventory.js
frontend/src/Components/Inventory/AllInventory.css
frontend/src/Components/Inventory/AllInventory.js
frontend/src/Components/Inventory/Inventory.css
frontend/src/Components/Inventory/Inventory.js
frontend/src/Components/Inventory/UniqueInventory.css
frontend/src/Components/Inventory/UniqueInventory.js
frontend/src/Components/Inventory/UpdateInventory.css

shift reorder level to upper level of the page. add the material UI dependencies.

shift reorder level to upper level of the page. add the material UI dependencies.

---

frontend/src/Components/Supplier/src/pages/supplierdata/index.jsx

fixed the update supplier fetching error

fixed the update supplier fetching error

---

frontend/package-lock.json
frontend/package.json
frontend/src/Components/Supplier/src/pages/supplierdata/UniqueSupplier.js
frontend/src/Components/Supplier/src/pages/supplierdata/UpdateSupplier.js
frontend/src/Components/Supplier/src/pages/supplierdata/index.jsx

Validate date correctly

---

frontend/package-lock.json
frontend/package.json
frontend/src/Components/Vehicle/src/pages/vehicledata/index.jsx
frontend/src/index.js

Added some  modules

---

frontend/src/Components/Supplier/src/pages/dashboard/index.jsx
frontend/src/Components/Supplier/src/pages/pie/index.jsx

add pie charts to the dashboars

add pie charts to the dashboars

---

backend/routes/fuelConsumption.js
frontend/package-lock.json
frontend/src/Components/Fuel/src/pages/dashboard/index.jsx
frontend/src/Components/Fuel/src/pages/fuelconsumtion/index.jsx
frontend/src/Components/Fuel/src/pages/fuelentry/AddFuelentry.js
frontend/src/Components/Fuel/src/pages/fuelentry/UpdateFuelentry.js
frontend/src/Components/Fuel/src/pages/fuelstock/AddFuelstock.js
frontend/src/Components/Fuel/src/pages/fuelstock/UniqueFuelstock.js
frontend/src/Components/Fuel/src/pages/fuelstock/UpdateFuelstock.css
frontend/src/Components/Fuel/src/pages/fuelstock/UpdateFuelstock.js
frontend/src/Components/package-lock.json
frontend/src/Components/package.json

Edited view of update and view Fuel stock

Edited view of update and view Fuel stock

---

frontend/src/Components/Inventory/src/components/BarChart.jsx
frontend/src/Components/Inventory/src/pages/dashboard/index.jsx
frontend/src/Components/Inventory/src/pages/global/sidebar/MyProSidebar.jsx
frontend/src/Components/Inventory/src/pages/inventorydata/index.jsx
frontend/src/Components/Inventory/src/pages/release/index.jsx
frontend/src/Components/Supplier/src/pages/supplierdata/UpdateSupplier.js

Adding the release spare parts functionality

Adding the release spare parts functionality

---

frontend/src/Components/Supplier/src/pages/supplierdata/index.jsx

adding mail function

---

frontend/src/Components/Fuel/src/pages/fuelentry/UniqueFuelentry.js

Edited Fuel Dispacth
